### ISSUE TITLE
Wrong wiki link

### ISSUE THREAD

**Issue by Binnette** [ToastHawaii/osm-apps-catalog#1]
Hi @ToastHawaii, thanks you for your OSM App Catalog. It is really cool :+1: 
I'm using it with the topic "editor" to update wiki article.

BTW, here is a little bug:
![image](https://user-images.githubusercontent.com/6597721/95783366-f438e680-0cd1-11eb-8191-2e02d0c9c40f.png)

For OsmHydrant, the "wiki" link redirect to https://wiki.openstreetmap.org/wiki/List%20of%20OSM-based%20services
Instead of https://wiki.openstreetmap.org/wiki/OsmHydrant

Can you please fix this bug? Have a nice day.

**Comment by ToastHawaii** [comment]
Thanks. :)

It's fixed.
It will be changed on the next update.

**Comment by Binnette** [comment]
Nice. Thank you @ToastHawaii  :+1:
