### ISSUE TITLE
Use of JSONP for taginfo API

### ISSUE THREAD

**Issue by joto** [ToastHawaii/osm-apps-catalog#127]
It seems you are using the JSONP feature of the taginfo API. At least I am seeing messages with `"GET /api/4/projects/all?callback=getTagInfoProjects HTTP/2.0"` in the taginfo log file with a referrer of `https://osm-apps.zottelig.ch/`.

We have had CORS for a long time now. Do you really need JSONP? I want to get rid of JSONP support in taginfo at some point. Thanks!

**Comment by ToastHawaii** [comment]
@joto Thank you for your taginfo project and the public API. :) I changed the code and removed the use of jsonp. I don't know why I used jsonp back then. 

I have published the change.
