### ISSUE TITLE
Can you hide "broken/discontinuated" software

### ISSUE THREAD

**Issue by Binnette** [ToastHawaii/osm-apps-catalog#2]
Hi @ToastHawaii, can you please hide "broken"/"discontinuated" softwares ?

![image](https://user-images.githubusercontent.com/6597721/95786989-e8045780-0cd8-11eb-8304-5987e993bbb8.png)

If you read the wiki article code, you will see `|status=broken` that indicate the software is no longer working.

The article : https://wiki.openstreetmap.org/wiki/POI-Witch

Thanks you :sun_with_face:

**Comment by ToastHawaii** [comment]
Hello @Binnette 
This is allready implemented. I add the status part to the sotware template for that purpose. ;)
The apps in the catalog get cached in the localstorage for a day. The POI-Witch is not displayed my system. Based on the history from the POI-Witch it should now not be visible on your system. Is it still displayed?

Best regards ToastHawaii

**Comment by Binnette** [comment]
I can no longer reproduce the bug. Thank you 😉
