### ISSUE TITLE
Wrong wiki link

### ISSUE THREAD

**Issue by Binnette** [ToastHawaii/osm-apps-catalog#3]
Hi again,

![image](https://user-images.githubusercontent.com/6597721/95789524-f9039780-0cdd-11eb-81bf-73edea82fedd.png)

The wiki link point to https://wiki.openstreetmap.org/wiki/User:Rfuegen/GpsMaster
Instead of https://wiki.openstreetmap.org/wiki/GpsMaster

Thank you :+1:

**Comment by ToastHawaii** [comment]
Yes, it is document like that in the template in the wiki page from GpsMaster: 

https://wiki.openstreetmap.org/w/index.php?title=GpsMaster&action=edit
```
...
|author=Rainer Fügenstein (Initial code by Matt Hoover)
|wiki=[[User:Rfuegen/GpsMaster|GpsMaster]]
|web=
...
```

**Comment by Binnette** [comment]
Thank you @ToastHawaii. Then I fixed the wiki article 😉
