### ISSUE TITLE
Minor: wiki template GitHub link should be replaces by URL

### ISSUE THREAD

**Issue by Binnette** [ToastHawaii/osm-apps-catalog#6]
Hi @ToastHawaii, here is a minor bug:
![image](https://user-images.githubusercontent.com/6597721/96980492-b03eb080-151f-11eb-8e02-384f23f38e5d.png)

Can you please replace this wikicode with the corresponding GitHub Url ?

Beware there can be multiple links 😉

**Comment by ToastHawaii** [comment]
Thanks. 
I fixed the code, it will be visible in one day.
